apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: elastic-deploy
data:
  elasticsearch.yml: |
    # Add your Elasticsearch configuration here
    cluster.name: my-cluster
    node.name: my-node
    network.host: 0.0.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elastic-deploy
spec:
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: 192.168.1.41:8082/docker-hosted/elasticsearch:1.0.${BUILD_NUMBER}
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: discovery.type
          value: single-node 
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
        - name: config-volume
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
      - name: elasticsearch-data
        emptyDir: {}
      - name: config-volume
        configMap:
          name: elasticsearch-config  
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elastic-deploy
spec:
  selector:
    app: elasticsearch
  ports:
  - name: http
    protocol: TCP
    port: 9200
    targetPort: 9200
  - name: transport
    protocol: TCP
    port: 9300
    targetPort: 9300
---
apiVersion: v1
kind: Secret
metadata:
  name: nexus-docker-secret
  namespace: argocd
data:
  .dockerconfigjson: ew0KICAgICJhdXRocyI6IHsNCiAgICAgICIxOTIuMTY4LjEuNDE6ODA4MiI6IHsNCiAgICAgICAgInVzZXJuYW1lIjogImFkbWluIiwNCiAgICAgICAgInBhc3N3b3JkIjogIjY4MGM0YWYzLWNhYjktNDMyOC04MjBlLWEwODI4YjNlNjFlNSIsDQogICAgICAgICJhdXRoIjogIllXUnRhVzQ2Tmpnd1l6Umhaak10WTJGaU9TMDBNekk0TFRneU1HVXRZVEE0TWpoaU0yVTJNV1UxIg0KICAgICAgfQ0KICAgIH0NCiAgfQ0KDQogIA0K
type: kubernetes.io/dockerconfigjson


