apiVersion: v1
kind: ConfigMap
metadata:
  name: my-filebeat
  namespace: elastic-deploy
data:
  my-file.log: |
    This
    You
    Make

---
apiVersion: v1
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - /usr/share/filebeat/my-file.log
        
    output.logstash:
      hosts: ['logstash:5044']

kind: ConfigMap
metadata:
  name: filebeat-configmap
  namespace: elastic-deploy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat
  namespace: elastic-deploy
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.15.0
        volumeMounts:
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
        - name: my-filebeat
          mountPath: /usr/share/filebeat/my-file.log
          subPath: my-file.log
      volumes:
       - name: filebeat-config
         configMap:
           name: filebeat-configmap
       - name: my-filebeat
         configMap:
           name: my-filebeat

