apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: elastic-deploy
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "filebeat-data"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: elastic-deploy
spec:
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: 192.168.1.41:8082/docker-hosted/logstash:1.0.${BUILD_NUMBER}
        ports:
        - containerPort: 5044  # Port for receiving logs from other containers
          name: logstash
        volumeMounts:
        - name: logstash-config
          mountPath: /usr/share/logstash/pipeline/logstash.conf
          subPath: logstash.conf
      volumes:
      - name: logstash-config
        configMap:
          name: logstash-configmap
 
          
---
kind: Service
apiVersion: v1
metadata:
  name: logstash
  namespace: elastic-deploy
spec:
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
---
apiVersion: v1
kind: Secret
metadata:
  name: nexus-docker-secret
  namespace: argocd
data:
  .dockerconfigjson: ew0KICAgICJhdXRocyI6IHsNCiAgICAgICIxOTIuMTY4LjEuNDE6ODA4MiI6IHsNCiAgICAgICAgInVzZXJuYW1lIjogImFkbWluIiwNCiAgICAgICAgInBhc3N3b3JkIjogIjY4MGM0YWYzLWNhYjktNDMyOC04MjBlLWEwODI4YjNlNjFlNSIsDQogICAgICAgICJhdXRoIjogIllXUnRhVzQ2Tmpnd1l6Umhaak10WTJGaU9TMDBNekk0TFRneU1HVXRZVEE0TWpoaU0yVTJNV1UxIg0KICAgICAgfQ0KICAgIH0NCiAgfQ0KDQogIA0K
type: kubernetes.io/dockerconfigjson


