apiVersion: v1
kind: Service
metadata:
  labels:
    app: new
  name: nexus-service
spec:
  selector:
    app: new
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: new
  namespace: argocd
spec:
  selector:
    matchLabels:
      app: new
  template:
    metadata:
      labels:
        app: new
    spec:
      containers:
      - name: nginx
        image: nginx
        
