apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus
  name: nexus-service
spec:
  selector:
    app: nexus
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: argocd
spec:
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nginx
        image: ${nexusImage}
        
