apiVersion: v1
kind: Secret
metadata:
  name: nexus-docker-secret
  namespace: argocd
data:
  .dockerconfigjson: <base64-encoded-content>
  #ew0KICAgICJhdXRocyI6IHsNCiAgICAgICIxOTIuMTY4LjEuNDE6ODA4MiI6IHsNCiAgICAgICAgInVzZXJuYW1lIjogImFkbWluIiwNCiAgICAgICAgInBhc3N3b3JkIjogIjY4MGM0YWYzLWNhYjktNDMyOC04MjBlLWEwODI4YjNlNjFlNSIsDQogICAgICAgICJhdXRoIjogImJhc2U2NCh1c2VybmFtZTpwYXNzd29yZCkiDQogICAgICB9DQogICAgfQ0KICB9DQoNCiAg
type: kubernetes.io/dockerconfigjson
